core:
  admin_user: admin
  admin_password: Tr@nquiL0Z2026
  admin_api_token: ""
  disable_admin_user: false
  editable_keys: true
  create_default_peer: false
  create_default_peer_on_creation: false
  re_enable_peer_after_user_enable: true
  delete_peer_after_user_deleted: false
  self_provisioning_allowed: false
  import_existing: true
  restore_state: true

backend:
  default: local
  local_resolvconf_prefix: tun.

advanced:
  log_level: info
  log_pretty: false
  log_json: false
  start_listen_port: 51820
  start_cidr_v4: 10.11.12.0/24
  start_cidr_v6: fdfd:d3ad:c0de:1234::0/64
  use_ip_v6: false
  config_storage_path: ""
  expiry_check_interval: 15m
  rule_prio_offset: 20000
  route_table_offset: 20000
  api_admin_only: true
  limit_additional_user_peers: 0

database:
  debug: false
  slow_query_threshold: "0"
  type: sqlite
  dsn: data/sqlite.db
  encryption_passphrase: ""

statistics:
  use_ping_checks: true
  ping_check_workers: 10
  ping_unprivileged: false
  ping_check_interval: 1m
  data_collection_interval: 1m
  collect_interface_data: true
  collect_peer_data: true
  collect_audit_data: true
  listening_address: :8787

mail:
  host: 127.0.0.1
  port: 25
  encryption: none
  cert_validation: true
  username: ""
  password: ""
  auth_type: plain
  from: Wireguard Portal <noreply@wireguard.local>
  link_only: false
  allow_peer_email: false

auth:
  ldap:
    - provider_name: "LDAP"
      url: ldap://srv_ldap:389
      bind_user: cn=srv_ldap_reader,dc=local,dc=host
      bind_pass: 8t83XsbYLeqNSEU
      base_dn: ou=Users,dc=local,dc=host
      login_filter: "(&(objectClass=organizationalPerson)(uid={{login_identifier}}))"        
      sync_filter: (&(objectClass=organizationalPerson))
      #sync_filter: (&(objectClass=organizationalPerson)(!userAccountControl:1.2.840.113556.1.4.803:=2)(mail=*))
      #disable_missing: true
      sync_interval: 5m      
      start_tls: false
      cert_validation: false
      field_map:
        user_identifier: uid
        display_name: cn
        email: mail
      # нужно настраивать аттрибут memberOf в LDAP... поэтому пока только локальные учетки
      #admin_group: cn=SG-VPN-ADMINS,ou=groups,local.host
      registration_enabled: true
      log_user_info: true
  webauthn:
    enabled: true
  min_password_length: 12
  hide_login_form: false

web:
  listening_address: :8888
  external_url: http://srv_wg_portal:8888
  site_company_name: WireGuard Portal
  site_title: WireGuard Portal
  session_identifier: wgPortalSession
  session_secret: very_secret
  csrf_secret: extremely_secret
  request_logging: false
  expose_host_info: false
  cert_file: ""
  key_File: ""

webhook:
  url: ""
  authentication: ""
  timeout: 10s
